### ISSUE TITLE
Moving file bug

### ISSUE THREAD

**Issue by YanceyChiew** [wa2c/cifs-documents-provider#1]
# 
### 1.1.0
---

### moving file
---

## Problem Description:  

when requesting to move a file, sometimes what the program actually does is to rename the source file to the name of the target directory (not including its parent directory), sometimes it does nothing or occasionally succeeds.

---

#### [/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L253](https://github.com/wa2c/cifs-documents-provider/blob/132146de088909cb0377c6b79853b4a63481f250/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L253)

```
suspend fun moveFile(sourceUri: String, targetUri: String): CifsFile? {
         return withContext(Dispatchers.IO) {
         //...
             Uri.parse(targetUri).lastPathSegment?.let { renameFile(sourceUri, it) }   // **H E R E**
         //...
        }
 }
```

The above code uses renaming to move files on the same server, but the new file name argument passed is only the last segment of the target uri.

#### [/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L203](https://github.com/wa2c/cifs-documents-provider/blob/132146de088909cb0377c6b79853b4a63481f250/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L203)  

```
    suspend fun renameFile(sourceUri: String, newName: String): CifsFile? {
        return withContext(Dispatchers.IO) {
            val targetUri = if (sourceUri.isDirectoryUri) {
                sourceUri.trimEnd('/').replaceAfterLast('/', newName) + '/'
            } else {
                sourceUri.replaceAfterLast('/', newName)                                         // **H E R E**
            }
```  

The uri of the target directory will be prefixed with the source file directory. This logic seems to only apply to renaming files in the same directory.

#### [/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L40](https://github.com/wa2c/cifs-documents-provider/blob/132146de088909cb0377c6b79853b4a63481f250/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L40)  

```
    /**
     * True if directory URI
     */
    private val String.isDirectoryUri: Boolean
        get() = this.endsWith('/')
```  

In the actual test, the directory uri did not end with "/",  and [#L205](https://github.com/wa2c/cifs-documents-provider/blob/132146de088909cb0377c6b79853b4a63481f250/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/domain/repository/CifsRepository.kt#L205)  is always false.

Therefore, if the source file and the target directory are at the same directory level, the move can be successful, otherwise it will have unpredictable consequences.

**Comment by wa2c** [comment]
Thank you for your report.
Your pull request works fine, so I merged it.
