### ISSUE TITLE
NonFree lib in F-Droid build

### ISSUE THREAD

**Issue by linsui** [wa2c/cifs-documents-provider#28]
com.google.android.gms:play-services-oss-licenses is not FOSS. See https://maven.google.com/com/google/android/gms/play-services-oss-licenses/12.0.0/play-services-oss-licenses-12.0.0.pom. Could you please replace with an FOSS alternative (see https://gitlab.com/-/snippets/1896503)? Thanks!

**Comment by wa2c** [comment]
Sorry, I'll fix it.

**Comment by wa2c** [comment]
I changed com.google.android.gms:play-services-oss-licenses to [AbountLibraries](https://github.com/mikepenz/AboutLibraries) on Ver.1.6.0.

**Comment by linsui** [comment]
Thanks!
