### ISSUE TITLE
Abnormally behavier with domain user

### ISSUE THREAD

**Issue by YanceyChiew** [wa2c/cifs-documents-provider#3]
At first I found that the program only works occasionally when using email as username.

Next, I read the jcifs code and found that when processing such usernames, the constructor of ntmlpasswordauthenticator will intercept the domain name in the mailbox and put it into another independent domain field.

At that time, I thought this was to be compatible with the format of directly writing the user name in the uri. The documentation of this class also said that the only special symbol that cannot be used is @.  I obtained the private constructor of the class through reflection, and successfully established a stable connection with the mailbox name. But this doesn't explain why I was able to obtain files occasionally before.

So I captured the packet and analyzed the other two software that can normally use the mailbox as the cifs user name, and found that the method of dividing the domain name and the user name in solid explorer can work normally, while the full mailbox name is used in fx explorer.

Obviously it is fraudulent to obtain the private constructor, and the login problem of domain users has not been substantially solved.

After tracking the program and reading the anr report, I finally found that using the domain username to obtain the smbfile would cause a deadlock to determine whether it was a trusted domain.  The reason is that the jcifs library regards the connection with the domain field as having the DFS service enabled, so it will try to read the named pipe under the target server, which is very arbitrary.

The solution is also clear. When the user knows that there is no DFS on the target server, optionally set the property for CIFScontent to manually disable the DFS，witch was enabled by default.

[/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/data/CifsClient.kt#L25](https://github.com/wa2c/cifs-documents-provider/blob/c07f7b48d72c0259710363a47e26a40188b4cf30/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/data/CifsClient.kt#L25)  

```
class CifsClient @Inject constructor() { /** * Get auth by user. Anonymous if user and password are empty. */ fun getConnection(user: String? = null, password: String? = null, domain: String? = null): CIFSContext { val property = Properties().apply { setProperty("jcifs.smb.client.minVersion", "SMB210") setProperty("jcifs.smb.client.maxVersion", "SMB300") setProperty("jcifs.smb.client.responseTimeout", READ_TIMEOUT.toString()) setProperty("jcifs.smb.client.connTimeout", CONNECTION_TIMEOUT.toString()) } return CIFSContextWrapper(BaseContext(PropertyConfiguration(property)) .withCredentials(NtlmPasswordAuthenticator(domain, user, password))) }

```  
Whether the following line is executed is up to the user to judge.  

`setProperty("jcifs.smb.client.dfs.disabled", true.toString())`

**Comment by YanceyChiew** [comment]
Wait, I celebrated too early. After disabling dfs, domain users can indeed get the file list normally, but all files become inaccessible. It seems that there is a problem with the structure of the file path.

**Comment by YanceyChiew** [comment]
> ~~Wait, I celebrated too early. After disabling dfs, domain users can indeed get the file list normally, but all files become inaccessible. It seems that there is a problem with the structure of the file path.~~  

It's my fault that not being able to get the file is a new bug I introduced inadvertently when analyzing return objects, and the solution above is feasible.

**Comment by wa2c** [comment]
OK, I tried the code and it works fine in my environment (accessed with my Windows Outlook account).

**Comment by YanceyChiew** [comment]
> https://github.com/wa2c/cifs-documents-provider/commit/d85f172b11499c32df445404677ca2ed1206408b

By default, the jcifs library regards the connection that uses the authentication with the domain field as using DFS, which is actually not sure, such as using an outlook account to log in to windows share.

Disabling DFS can allow domain users who do not use DFS to correctly obtain shared files, but it will interfere with real DFS user authentication and access to shared files on different servers.  So I think that a more general solution is for domain users, adding a switch to whether to use DFS in the settings.🙂

**Comment by wa2c** [comment]
https://github.com/wa2c/cifs-documents-provider/commit/f842baa76a2c827afdc1655931d6d49eeae413da
I added the option to use DFS  in this commit. That's OK?

<img src="https://user-images.githubusercontent.com/14200387/113611443-7b678580-9689-11eb-9566-6ae35f912047.png" width="200" />

**Comment by YanceyChiew** [comment]
> https://github.com/wa2c/cifs-documents-provider/commit/f842baa76a2c827afdc1655931d6d49eeae413da
> I added the option to use DFS  in this commit. That's OK?

It's perfect👍

**Comment by wa2c** [comment]
Ver. 1.2.0 released.
It contains this modification.
Thank you.

**Comment by YanceyChiew** [comment]
This application you developed is useful, and being able to make a small contribution to its improvement is my pleasure.😊

**Comment by wa2c** [comment]
I close this issue. Thank you.
