### ISSUE TITLE
Build for Lower Android Versions 6.0+

### ISSUE THREAD

**Issue by samysousa** [wa2c/cifs-documents-provider#37]
Comparing to Android Samba Client which was available on Android 6.0.
It would be a great if it was able to compile for Android 6 instead of requiring 8.0

Target would be Amazon Firestick. 
App was even published on Amazon Appstore Store, but cannot install due to version of Android (Fire OS 6/Android 7.1 in my case)

Fire OS 5: Based on Android 5.1 (Lollipop, API level 22)
Fire OS 6: Based on Android 7.1 (Nougat, API level 25)
Fire OS 7: Based on Android 9 (Pie, API level 28)

Most Firesticks are running Fire OS 6, so minimum here would be 7.1 
Ideally Fire OS 5 would also be supported.

Is this even possible ?

**Comment by wa2c** [comment]
Sorry, it is not possible.
This app uses [ProxyFileDescriptorCallback](https://developer.android.com/reference/android/os/ProxyFileDescriptorCallback) for file reading/writing. It needs Android 8.0 or over. 

Additionally,  upload apps to the store probably won't be able to support lower OS versions.
