### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by narsei** [wa2c/cifs-documents-provider#40]
where can i find the mount after enabling local storage?

**Comment by RebelliousX** [comment]
![Screenshot 2023-08-15 032542](https://github.com/wa2c/cifs-documents-provider/assets/1888186/04aefdb6-62d5-4419-8989-94ba788e0a06)

**Comment by RebelliousX** [comment]
Very handy feature and unique to this wonderful application. Thanks w2c for implementing this again. I am using this extensively.
