### ISSUE TITLE
AndroidTV navigation is broken

### ISSUE THREAD

**Issue by KyleSanderson** [wa2c/cifs-documents-provider#43]
Version 1.7.0 (17) 

You can't select the new folder or anything, and it's nearly impossible to navigate around. I'm sure this is a great app, but it's been this way since last year 😢

**Comment by wa2c** [comment]
I have no Android TV...
Since I can't reproduce the event, I don't know the cause.
Currently, this app does not support Android TV.

https://github.com/wa2c/cifs-documents-provider/issues/32

According to the issue above, regular Android TV does not seem to support storage a.

**Comment by RebelliousX** [comment]
Android TV doesn't have file picker app (native Files app, com.android.documentsui, even if you install it, it won't register the intents and the system won't honor the requests). Only Android TV has this is the Shield TV, but it has built in SMB support that can mount the share as local storage anyway.
