### ISSUE TITLE
Finding share in Word

### ISSUE THREAD

**Issue by brhunt1958** [wa2c/cifs-documents-provider#45]
Hello,

This may be a misunderstanding on my part, but I thought that I would see a connected device in other Android apps?

I created an SMB connection in CDP.  I have Use As Local Storage selected and I have rebooted.

When I open MS Word for Android, I cannot see the device, folder or files anywhere.

Have I missed a step?

Thanks.

Bryan Hunt

**Comment by RebelliousX** [comment]
It worked for me. When you see the initial screen that says Recents, at the bottom left it says "open other documents" just above where it says "Go premium" (unless you already have 365 subscription).  Then the "Open" window pops up or slides in in my case, just tap "Browse" that has a cloud icon. The file picker will show up and CIFS Document Provider will be one ofthe mounts on the left.

**Comment by brhunt1958** [comment]
Thaer,

I rebooted the phone a second time and the CIFS connection now shows.  Not quite sure what happened, but it is working fine now, thanks.

I will close this issue.

Bryan Hunt
