### ISSUE TITLE
When I use SMBJ rename method is failed.

### ISSUE THREAD

**Issue by SNUyi** [wa2c/cifs-documents-provider#48]
I think this 
com.wa2c.android.cifsdocumentsprovider.data.storage.smbj.SmbjClient#renameFile paramer is wrong.
And openFile should use AccessMask.GENERIC_ALL, could rename file.

**Comment by RebelliousX** [comment]
I tried to change the AccessMask to GENERIC_ALL but still it doesn't work.

Line 281 of SMBjClient.kt
`diskEntry.rename(targetConnection.name)`   <- renames the file with the same name as current folder
should be
`diskEntry.rename(targetConnection.sharePath)` <- correctly renames the file

But in both cases, we will get error bubble in the `Files` stating the rename failed (although the second one succeeded). But this is only for files. It doesn't even work for directories. If it was a directory, an exception will be thrown complaining it was a directory and not a file.

**Comment by SNUyi** [comment]
@RebelliousX for example，
open directory:
diskShare.openDirectory(oldPath,
            EnumSet.of(AccessMask.GENERIC_ALL),
            null,
            SMB2ShareAccess.ALL,
            SMB2CreateDisposition.FILE_OPEN,
            null)

open file：
diskShare.openFile(
            sharePath,
            EnumSet.of(AccessMask.GENERIC_ALL),
            EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
            SMB2ShareAccess.ALL,
            SMB2CreateDisposition.FILE_OPEN,
            null
        )
it works to me.
And diskFile.rename() paramer like this "1_6\image9_6.pdf"  "1_6" is parent directory.

**Comment by wa2c** [comment]
@SNUyi 
I found the cause of this problem.
Fix in next version.

https://github.com/wa2c/cifs-documents-provider/commit/4f2280c0e9667d476e6ee5fa48a7346a15d68519

**Comment by SNUyi** [comment]
> @SNUyi I found the cause of this problem. Fix in next version.
> 
> [4f2280c](https://github.com/wa2c/cifs-documents-provider/commit/4f2280c0e9667d476e6ee5fa48a7346a15d68519)

**Comment by SNUyi** [comment]
@wa2c Well done

**Comment by wa2c** [comment]
@SNUyi 
Ver.2.0.0 released. Please check it.
