### ISSUE TITLE
Any plans to submit this to f-droid?

### ISSUE THREAD

**Issue by dbrand666** [wa2c/cifs-documents-provider#5]

**Comment by wa2c** [comment]
I hadn't thought about it, but I will consider it.

**Comment by wa2c** [comment]
@dbrand666 
[Request For Packaging: CIFS Documents Provider \(\#1827\) · Issues · F\-Droid / Requests For Packaging · GitLab](https://gitlab.com/fdroid/rfp/-/issues/1827)

I requested for packaging. (Currently not released yet.)

**Comment by yumemi-awada** [comment]
@dbrand666 
https://www.f-droid.org/ja/packages/com.wa2c.android.cifsdocumentsprovider/

This app was released on F-Droid.
I close this issue.
Thank you.

**Comment by wa2c** [comment]
@dbrand666 
https://www.f-droid.org/ja/packages/com.wa2c.android.cifsdocumentsprovider/

This app was released on F-Droid.
I close this issue.
Thank you.

**Comment by dbrand666** [comment]
Thank you!
