### ISSUE TITLE
Server for Memento Database

### ISSUE THREAD

**Issue by ttc161** [wa2c/cifs-documents-provider#63]
Greetings!
Is it possible to organize the server operation for the Memento Database application? Using the developer's server for personal purposes is expensive for me. The limit for the free version is not enough (3 libraries or 100 MB).
The program's [website](https://mementodatabase.com/). I use Android and Windows.
Perhaps you can suggest how to do this, or add functionality to use your application as a Memento database server.
Thanks!

**Comment by wa2c** [comment]
No thanks
