### ISSUE TITLE
Where is the local storage folder?

### ISSUE THREAD

**Issue by SiLenCe-WB** [wa2c/cifs-documents-provider#65]
I've just installed this app on a Pixel 3a (Android 12) and I've managed to mount the smb share without issues. I have tested it like this:

1. Create a new email on gmail.
2. Attach a document.
3. Select "Open From" (three bars menu).
4. Chose CIFS Documents Provider.

When I chose it, it shows the IP address of my NAS and when I tap on it, I get access to the files that I previously configured on the app.

My problem is that I'm trying to figure out **where is the local folder in my device**. I thought the point of this app was to mount an SMB share on a local folder of your choosing, but there is no option to select a local folder, even though I have ticked "Use as local folder" box and rebooted. Does the app create one folder inside my phone with that share? And if that is the case, where is it?

**Comment by RebelliousX** [comment]
@SiLenCe-WB Unfortunately, it doesn't do what you want. The setting `Use as local storage` means that any 3rd party application expects a local storage from Android's SAF (Storage Access Framework), a.k.a, the default Files app. 

If this setting is `Off` and the 3rd party application can't see your SMB share from the `Files` app when you are trying to open it. Then that application expects a local storage files "**only**". Turning this setting `On`, is just to emulate that behavior, and you might be surprised that the same 3rd party app now see your files. 

This is not perfect, but it works very well on most applications I have found; minus some that require input/output stream like video recording applications.

**Comment by SiLenCe-WB** [comment]
Yeah, it works very nicely 👌👌

I guess that in other to mount a SMB share on a folder you need root permissions anyway, right?

**Comment by RebelliousX** [comment]
Correct. If you are rooted, and If you want to go down the rabbit hole, look into RClone sync for android.

**Comment by wa2c** [comment]
@RebelliousX 
Thank you! 

@SiLenCe-WB 
I don't think this app is for the purpose you expect.
I hope this app is useful for you.

**Comment by biagioDO** [comment]
Sorry for reopening this issue.
My problem is not related to the "Use as local storage" option, but I don't know how to turn on the Storage Access Framework setting
