### ISSUE TITLE
Problems with character # on filenames

### ISSUE THREAD

**Issue by marevalo** [wa2c/cifs-documents-provider#7]
I have a directory with serveral files with # character like this:

![ls](https://user-images.githubusercontent.com/1233075/132643438-33626ee9-52a5-4135-b2da-b22d672e440f.png)

But on the phone the first file is repeated n times:

![photo5895355141253609125](https://user-images.githubusercontent.com/1233075/132643552-1a0a701f-274e-4d52-b371-13bf46c0d0b5.jpg)

Environment:

App version: 1.3.0 from Google Play
Android 10, LineageOS 17.1 (but also on my Galaxy Tab 6 Lite with Android 11)
SMB: Samba 4.9.5

**Comment by wa2c** [comment]
I'm sorry, I'll fix it now.

**Comment by wa2c** [comment]
@marevalo 
I fixed this problem and  released ver.1.3.1 now.

**Comment by marevalo** [comment]
Thanks a lot, I see it fixed now. It's great that it took only one day from filing the bug to have a fixed apk.
