### ISSUE TITLE
Can't import private key for SFTP

### ISSUE THREAD

**Issue by lsaa** [wa2c/cifs-documents-provider#73]
I tried making a key on my phone through termux but when referring to the file I get the error `Failed to read the private key`. I tried with all the options for `ssh-keygen` (rsa, dsa, ecdsa and ed25519) and all of them give the same error.

The RSA keys work fine on other apps that need it like `ConnectBot` and `Material Files`.

Connecting with a password works but I'd rather not have that be allowed.

**Comment by wa2c** [comment]
@lsaa 
Hey, thank you for reporting this problem.

Upon investigation, I found that JSch library does not support reading new format private key files.
https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

I replace the library with the forked library https://github.com/mwiede/jsch .

This fix will be included in the next version.
https://github.com/wa2c/cifs-documents-provider/commit/a92f2e656e55e259e95765e8f63443d88c07b14e

**Comment by lsaa** [comment]
Built it and tested, looks good to me

**Comment by lsaa** [comment]
Closing this as latest distributed version works <3
