### ISSUE TITLE
SFTP: Check the server's ssh host key

### ISSUE THREAD

**Issue by 1cook** [wa2c/cifs-documents-provider#77]
**Is your feature request related to a problem? Please describe.**
When I change the value of HostKey in my sshd_config on my server (the private key that the server uses to identify itself to the client) and restart the server, cifs-documents-provider continues to connect to my server without warning me that the host key has changed.

The file ApacheSftpClient.kt appears to call setStrictHostKeyChecking and sets the value to "no". By reading the ssh_config man page, we find that the option "no" allows connections to proceed even when the host key has changed.

**Describe the solution you'd like**
When connecting to the server for the first time, the PC ssh client displays the server's host key fingerprint and asks the user whether or not this is the correct key. If the user confirms the key, then it is stored in the user's ~/.ssh/known_hosts file as a known good key. If the server's host key then changes, then the client will warn the user that the key has been changed.

cifs-documents-provider should ask the user whether or not the fingerprint is correct, store the server's host key and check it on all connections

**Describe alternatives you've considered**
I don't know of any alternative solutions.

**Additional context**
Failure to check the server's host key can lead to man-in-the-middle attacks without the client noticing.

This is a serious shortcoming. I would not rely on this app for sensitive files unless it checks the host key.

**Comment by wa2c** [comment]
@1cook 
Thank you for your feedback.
In the next version, check known hosts.

**Comment by wa2c** [comment]
@1cook 
Ver.2.3.0 released. Please check it.

**Comment by RebelliousX** [comment]
I tested this on v2.3.0. I don't know how it was before this version (I was unfortunately using passwords until I got fed up with 10s of email Alerts daily from my TrueNAS that someone failed to log in using SSH, thus, I switched to keys and disabled password logins, lol). 

But in this one I changed the public key on the server and I can't connect until I put the right private key to CIFS Document Provider, which is the correct behavior.

If it wasn't before, then it is fixed. 🫡

I gotta say, damn, it is really nice and SFTP much faster than FTP/FPTS (but not SMB, but close), even when accessing my TrueNAS from WAN. Loading times while playing in emulators are very negligible.

**Comment by 1cook** [comment]
@wa2c 
I checked the new behavior by changing the value of _HostKey_ in _/etc/ssh/ssh_config_ and reloading the server config.
The behavior appears correct. Thanks.

**Comment by 1cook** [comment]
@RebelliousX I'm sorry, I don't understand the point that you are trying to make here, or how this is relevant to the issue. I am under the impression that you are confusing the **host's** public key with the **client's** public key. While both are stored in the same formats and can be created with _ssh-keygen_, they serve different purposes.

I reccomend reading the _Authentcation_ section of the openssh manual page: https://man.openbsd.org/ssh#AUTHENTICATION
This medium article looks easier to read:
https://medium.com/hackernoon/ssh-keys-a-primer-7ac8b790e849

The gist of it is that ssh authentication must go BOTH ways. Just as the server authenticates the client with the client's public key, the client authenticates the server with the server's public key (referred to in the manual as the host key). While you have to manually configure public key authentication for your client, your linux distro automatically configures the host keys for you during the installation of openssh. For this reason, you may not have noticed that you even needed a host key.

**Comment by RebelliousX** [comment]
@1cook You are correct. I only knew about the existence of private and private keys, I learned about the bare minimum to get ssh working. Thanks for the articles, I will read them 👍🏻

**Comment by abirhasan132** [comment]
#77

**Comment by 1cook** [comment]
host key checking is implemented
