### ISSUE TITLE
allow copying the folder URI

### ISSUE THREAD

**Issue by aguaviva** [wa2c/cifs-documents-provider#9]
Right now it is displayed in the "connection" panel but it cannot be copied so it can be used in apps that dont support the content picker.

Man, your app is awsome, it even supports a custom port!!

**Comment by wa2c** [comment]
@aguaviva 
<img src="https://user-images.githubusercontent.com/14200387/135654205-83802a05-da07-4f51-be2c-1b559a020a11.png" width="200" />

I plan to change the URI text to be selectable.
Does it meet your requirements?

**Comment by aguaviva** [comment]
Spot on! Much appreciated! :)

**Comment by wa2c** [comment]
@aguaviva 
Ver.1.3.2 released. It supports URI selection.

**Comment by aguaviva** [comment]
Awesome!!! Many thanks :)

**Comment by yumemi-awada** [comment]
Close this issue.
Thank you

**Comment by wa2c** [comment]
Close this issue.
Thank you.
